if SpeachPart.all.empty?
  SpeachPart.create en: 'noun',         de: 'Substativ',    ru: 'существительное'
  SpeachPart.create en: 'adjective',    de: 'Adjektiv',     ru: 'прилагательное'
  SpeachPart.create en: 'verb',         de: 'Verb',         ru: 'глагол'
  SpeachPart.create en: 'numeral',      de: 'Numerale',     ru: 'числительное'
  SpeachPart.create en: 'adverb',       de: 'Adverb',       ru: 'наречие'
  SpeachPart.create en: 'article',      de: 'Artikel',      ru: 'артикль'
  SpeachPart.create en: 'preposition',  de: 'Präposition',  ru: 'предлог'
  SpeachPart.create en: 'conjunction',  de: 'Konjuktion',   ru: 'союз'
  SpeachPart.create en: 'particle',     de: 'Partikel',     ru: 'частица'
  SpeachPart.create en: 'interjection', de: 'Interjektion', ru: 'междометие'
  SpeachPart.create en: 'pronoun',           de: 'Pronomen',         ru: 'местоимение'
  SpeachPart.create en: 'personal pronoun',  de: 'Personalpronomen', ru: 'личное местоимение'
  SpeachPart.create en: 'reflexive pronoun', de: 'Reflexivpronom',   ru: 'возвратное местоимение'
  SpeachPart.create en: 'possessiv pronoun',               de: 'Possessivpronom',    ru: 'притяжательное местоимение'
  SpeachPart.create en: 'demonstrative pronoun',           de: 'Demonstrativpronom', ru: 'указательное местоимение'
  SpeachPart.create en: 'indefinite pronoun',              de: 'Indefinitpronomen',  ru: 'неопределённое местоимение'
  SpeachPart.create en: 'relative, interrogative pronoun', de: 'Relativpronom, Interrogativpronom', ru: 'вопросит. и относит местоимение'
end
